version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8003
    ports:
      - "8003:8003"
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  
  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A config worker -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A config beat -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis

volumes:
  postgres_data: