version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8003
    ports:
      - "8003:8003"
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - celery
      - celery-beat
      - db
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    command: celery -A config worker -l info
    env_file:
      - ./.env.prod
    volumes:
      - ./usr/src/app/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  celery-beat:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    command: celery -A config beat -l info
    env_file:
      - ./.env.prod
    volumes:
      - ./usr/src/app/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  postgres_data:
  static_volume:
  media_volume:
  celery_volume:
