version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8003
    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
      - ./celery:/home/app/web
      - ./celery-beat:/home/app/web
    ports:
      - 8003:8003
    expose:
      - 8003
    env_file:
      - ./.env.prod 
    depends_on:
      - redis
      - celery
      - celery-beat
      - db
    logging:
      options:
        max-size: 10m

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    logging:
      options:
        max-size: 10m

  redis:
    image: redis

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.prod

  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.prod

volumes:
  postgres_data:
  static_volume:
  media_volume: