version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8003
    ports:
      - "8003:8003"
    volumes:
      - .:/home/user/web
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  
  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A nyct_bot worker -l info
    volumes:
      - .:/home/user/web
    env_file:
      - ./.env.prod.db
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build:
      context: .
    command: celery -A nyct_bot beat -l info
    volumes:
      - .:/home/user/web
    env_file:
      - ./.env.prod
    depends_on:
      - redis

volumes:
  pg_data: